### ISSUE TITLE
Logstash cannot create new index after updating config and restarting logstash

### ISSUE THREAD

**Issue by iboware** [floragunncom/search-guard-ssl#25]
I am not sure if this is a search-guard or search-guard-ssl problem but it is for sure a search-guard* related problem. This scenario was working before installing and configuring search-guard. Here is the problem with repro steps:
1 - Restart  ElasticSearch
2 - Add a new input plugin config to logstash (added config details below).
3 - Start Logstash
4 - Logstash will create a new index for the new config
5 - Logstash will generate  bulk insert queries and add them to the new index.
6 - Stop logstash
7 - Repeat Step 2 and 3
8 - Logstash won't be able to create new index and will generate no error log about that.
9 - Logstash will try to insert bulk queries but it will result with a no index found error, because there is no created index in es.
10 - There will be unassigned shards in ES and cluster health will turn to red.
11 - Restart ElasticSearch node connected by logstash and logstash itself.  Index will be created and bulk queries will be restarted successfully, like the first time.

I don't know why it does not work without restarting es. Maybe something blocking the connection for some reason?

**Logstash Config**
```
input {
#elasticsearch test account
    couchdb_changes {
      db => "tenant1738"
      host => "server.mycouchdb.com"
      username=>'user'
      password=>'pass'
      sequence_path=> '/config-dir/sequences/tenant1738.seq'
      add_field => {
        "tenant" => "tenant1738"
      }
# here I add other couchdb_changes configurations, which works well without activating search-guard
  }
output {
 elasticsearch {
      document_id => "%{[@metadata][_id]}"
      document_type=> "%{[doc][type]}"
      hosts => ["elastic1.server.com"]
      index => "%{[tenant]}"
      ssl => true
      ssl_certificate_verification => true
      keystore => '/config-dir/web-keystore.jks'
      keystore_password => '*****'
      truststore => '/config-dir/web-truststore.jks'
      truststore_password => '******'
      user => logstash
      password => '***********'
     }
}
```

**ES Configuration:**

```
#SearchGuard
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: /usr/share/elasticsearch/config/web-keystore.jks
searchguard.ssl.http.keystore_password: '********/'
searchguard.ssl.http.truststore_filepath: /usr/share/elasticsearch/config/web-truststore.jks
searchguard.ssl.http.truststore_password: '*******/'
searchguard.ssl.transport.keystore_filepath: /usr/share/elasticsearch/config/elastic1-keystore.jks
searchguard.ssl.transport.keystore_password: '**********/'
searchguard.ssl.transport.truststore_filepath: /usr/share/elasticsearch/config/truststore.jks
searchguard.ssl.transport.truststore_password: '*********/'
searchguard.ssl.transport.enforce_hostname_verification: true
#searchguard.ssl.transport.resolve_hostname: true
searchguard.authcz.admin_dn:
  - "CN=admin,OU=client,O=client,L=Test,C=DE"
searchguard.ssl.transport.enable_openssl_if_available: true
searchguard.ssl.http.enable_openssl_if_available: true
```
**sg_roles.yml (partial)**

```
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
    - indices:data/write/bulk*
  indices:
    '*':
      '*':
        - indices:data/write/bulk*
        - indices:data/write/update*
        - indices:data/write/index*
        - indices:data/write/delete*
    'logstash-*':
      '*':
        - CRUD
        - CREATE_INDEX
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX
```
**System Configuration:**

- Debian 8
- Oracle JDK 8
- OpenSSL 1.0.2h
- netty-tcnative-1.1.33.Fork17-linux-x86_64
- search-guard-ssl/2.3.3.11
- search-guard-2/2.3.3.0-rc1
- ES 2.3.3
- Kibana 4.5

**Comment by floragunncom** [comment]
Assume ``%{[tenant]}``will be resolved to ``tenant1738`` then you config have to look like:
<pre>
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
  indices:
    'tenant*': ### crud/createindex permissions for all tenant indices
      '*':
        - CRUD
        - CREATE_INDEX
</pre>

**Comment by iboware** [comment]
Yeah, but my role configuration works as it is for the first run, after restarting Elasticsearch, it creates the index.  No permission issue. When I update Logstash configuration and  restart *only* Logstash, it won't create the new index added by new configuration entry and this situation will happen. It works and creates the index only If I restart es. I will try your suggestion and update here.

**Comment by floragunncom** [comment]
ah ok, thats awkward, will also dig into this

**Comment by floragunncom** [comment]
Can you locate the first (successful) creation of the index in the logs (on DEBUG level)? normally it should look like that:

<pre>
[2016-06-17 21:53:17,421][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'logstash' is in cache? true (cache size: 4)
[2016-06-17 21:53:17,421][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'User [name=logstash, roles=[]]' is authenticated
[2016-06-17 21:53:17,422][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] evaluate permissions for User [name=logstash, roles=[]]
[2016-06-17 21:53:17,422][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested indices:admin/create from 127.0.0.1:60682
[2016-06-17 21:53:17,422][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Resolve [logstash-1] from class org.elasticsearch.action.admin.indices.create.CreateIndexRequest
[2016-06-17 21:53:17,422][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] indicesOptions IndicesOptions[id=48, ignore_unavailable=false, allow_no_indices=false, expand_wildcards_open=false, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=false, forbid_closed_indices=true]
[2016-06-17 21:53:17,422][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] raw indices [logstash-1]
[2016-06-17 21:53:17,422][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Cannot resolve [logstash-1] so we use the raw values
[2016-06-17 21:53:17,422][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved aliases and indices: [logstash-1]
[2016-06-17 21:53:17,422][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved types: [_all]
[2016-06-17 21:53:17,422][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] mapped roles: [sg_logstash, sg_public]
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] ---------- evaluate sg_role: sg_logstash
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Try wildcard match for *beat*
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   No wildcard match found for *beat*
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] For index *beat* remaining requested aliases and indices: [logstash-1]
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] For index *beat* remaining requested resolved types: [_all]
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Try wildcard match for logstash-*
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Wildcard match for logstash-*: [logstash-1]
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   matches for logstash-*, will check now types [*]
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]     resolvedActions for logstash-*/*: [indices:data/write*, indices:admin/create, indices:data/read*]
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]     match requested action indices:admin/create against logstash-*/*: [indices:data/write*, indices:admin/create, indices:data/read*]
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] For index logstash-* remaining requested aliases and indices: []
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] For index logstash-* remaining requested resolved types: []
[2016-06-17 21:53:17,423][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] found a match for 'sg_logstash.logstash-*', evaluate other roles
[2016-06-17 21:53:17,424][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] sg_role sg_public is empty
</pre>

And can you locate also the second (unsuccessful) creation in the logs? Should look like this:

<pre>
[2016-06-17 21:48:52,457][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'logstash' is in cache? false (cache size: 3)
[2016-06-17 21:48:52,457][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] logstash (408611584) not cached, return from internal backend directly
[2016-06-17 21:48:52,791][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'User [name=logstash, roles=[]]' is authenticated
[2016-06-17 21:48:52,792][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] evaluate permissions for User [name=logstash, roles=[]]
[2016-06-17 21:48:52,792][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested indices:admin/create from 127.0.0.1:60582
[2016-06-17 21:48:52,792][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Resolve [twitter] from class org.elasticsearch.action.admin.indices.create.CreateIndexRequest
[2016-06-17 21:48:52,793][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] indicesOptions IndicesOptions[id=48, ignore_unavailable=false, allow_no_indices=false, expand_wildcards_open=false, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=false, forbid_closed_indices=true]
[2016-06-17 21:48:52,793][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] raw indices [twitter]
[2016-06-17 21:48:52,793][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Cannot resolve [twitter] so we use the raw values
[2016-06-17 21:48:52,793][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved aliases and indices: [twitter]
[2016-06-17 21:48:52,793][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved types: [_all]
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] mapped roles: [sg_logstash, sg_public]
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] ---------- evaluate sg_role: sg_logstash
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Try wildcard match for *beat*
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   No wildcard match found for *beat*
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] For index *beat* remaining requested aliases and indices: [twitter]
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] For index *beat* remaining requested resolved types: [_all]
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Try wildcard match for logstash-*
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   No wildcard match found for logstash-*
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] For index logstash-* remaining requested aliases and indices: [twitter]
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] For index logstash-* remaining requested resolved types: [_all]
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] sg_role sg_public is empty
[2016-06-17 21:48:52,794][INFO ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] No perm match for indices:admin/create and [sg_logstash, sg_public]
[2016-06-17 21:48:52,794][DEBUG][com.floragunn.searchguard.filter.SearchGuardFilter] no permissions for indices:admin/create
</pre>

**Comment by iboware** [comment]
Hi,
These are the results that I could obtain as a result of many trials for hours. I hope it could help you to address the issue.

**Succesfull (After ES Restart)**
```
[2016-06-17 20:42:20,826][DEBUG][netty.handler.ssl.SslHandler] [id: 0x31c1414d, /my.ip.add.ress:45170 => /10.0.0.4:9200] HANDSHAKEN: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
[2016-06-17 20:42:20,848][DEBUG][com.floragunn.searchguard.http.XFFResolver] xff resolve /my.ip.add.ress:45170
[2016-06-17 20:42:20,848][DEBUG][com.floragunn.searchguard.http.XFFResolver] no xff done true,false,class org.elasticsearch.http.netty.NettyHttpRequest,{}
[2016-06-17 20:42:20,848][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] Try to extract auth creds from http basic 
[2016-06-17 20:42:20,848][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'logstash' is in cache? false (cache size: 1)
[2016-06-17 20:42:20,849][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] logstash (1425127881) not cached, return from internal backend directly
[2016-06-17 20:42:21,462][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'User [name=logstash, roles=[]]' is authenticated
[2016-06-17 20:42:21,463][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] evaluate permissions for User [name=logstash, roles=[]]
[2016-06-17 20:42:21,463][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested indices:admin/template/get from my.ip.add.ress:45170
[2016-06-17 20:42:21,463][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] class org.elasticsearch.action.admin.indices.template.get.GetIndexTemplatesRequest is not an IndicesRequest
[2016-06-17 20:42:21,463][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved aliases and indices: [_all]
[2016-06-17 20:42:21,463][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved types: [_all]
[2016-06-17 20:42:21,468][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] mapped roles: [sg_logstash, sg_public]
[2016-06-17 20:42:21,469][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] ---------- evaluate sg_role: sg_logstash
[2016-06-17 20:42:21,469][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   resolved cluster actions:[indices:admin/template/put, indices:admin/template/get]
[2016-06-17 20:42:21,469][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   found a match for 'sg_logstash' and indices:admin/template/get, skip other roles
[2016-06-17 20:42:22,477][DEBUG][com.floragunn.searchguard.http.XFFResolver] xff resolve /my.ip.add.ress:45170
[2016-06-17 20:42:22,478][DEBUG][com.floragunn.searchguard.http.XFFResolver] no xff done true,false,class org.elasticsearch.http.netty.NettyHttpRequest,{}
[2016-06-17 20:42:22,478][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] Try to extract auth creds from http basic 
[2016-06-17 20:42:22,478][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'logstash' is in cache? true (cache size: 2)
[2016-06-17 20:42:22,478][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'User [name=logstash, roles=[]]' is authenticated
[2016-06-17 20:42:22,519][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] evaluate permissions for User [name=logstash, roles=[]]
[2016-06-17 20:42:22,519][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested indices:data/write/bulk from my.ip.add.ress:45170
[2016-06-17 20:42:22,519][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Resolve [tenant1292] from class org.elasticsearch.action.index.IndexRequest
[2016-06-17 20:42:22,520][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] indicesOptions IndicesOptions[id=48, ignore_unavailable=false, allow_no_indices=false, expand_wildcards_open=false, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=false, forbid_closed_indices=true]
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] mapped roles: [sg_logstash, sg_public]
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] ---------- evaluate sg_role: sg_logstash
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Try wildcard match for tenant*
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Wildcard match for tenant*: [tenant1292]
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   matches for tenant*, will check now types [*]
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]     resolvedActions for tenant*/*: [indices:data/write*, indices:admin/create, indices:data/read*]
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]     match requested action indices:data/write/bulk against tenant*/*: [indices:data/write*, indices:admin/create, indices:data/read*]
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] remaining requested aliases and indices: []
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] remaining requested resolved types: []
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] found a match for 'sg_logstash', evaluate other roles for fls/dls purposes
[2016-06-17 20:42:22,591][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] sg_role sg_public is empty
[2016-06-17 20:42:22,609][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] evaluate permissions for User [name=logstash, roles=[]]
[2016-06-17 20:42:22,609][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested indices:admin/create from my.ip.add.ress:45170
[2016-06-17 20:42:22,609][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Resolve [tenant1292] from class org.elasticsearch.action.admin.indices.create.CreateIndexRequest
[2016-06-17 20:42:22,611][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] indicesOptions IndicesOptions[id=48, ignore_unavailable=false, allow_no_indices=false, expand_wildcards_open=false, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=false, forbid_closed_indices=true]
[2016-06-17 20:42:22,611][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] raw indices [tenant1292]
[2016-06-17 20:42:22,611][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Cannot resolve [tenant1292] so we use the raw values
[2016-06-17 20:42:22,611][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved aliases and indices: [tenant1292]
[2016-06-17 20:42:22,611][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved types: [_all]
[2016-06-17 20:42:22,611][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] mapped roles: [sg_logstash, sg_public]
[2016-06-17 20:42:22,611][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] ---------- evaluate sg_role: sg_logstash
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Try wildcard match for tenant*
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   Wildcard match for tenant*: [tenant1292]
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   matches for tenant*, will check now types [*]
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]     resolvedActions for tenant*/*: [indices:data/write*, indices:admin/create, indices:data/read*]
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]     match requested action indices:admin/create against tenant*/*: [indices:data/write*, indices:admin/create, indices:data/read*]
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] remaining requested aliases and indices: []
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] remaining requested resolved types: []
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] found a match for 'sg_logstash', evaluate other roles for fls/dls purposes
[2016-06-17 20:42:22,612][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] sg_role sg_public is empty
```

**Error after stopping Logstash**
```
[2016-06-17 21:33:39,962][DEBUG][netty.handler.ssl.SslHandler] Failed to clean up SSLEngine.
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
	at io.netty.handler.ssl.OpenSslEngine.closeInbound(OpenSslEngine.java:910)
	at org.jboss.netty.handler.ssl.SslHandler.closeEngine(SslHandler.java:591)
	at org.jboss.netty.handler.ssl.SslHandler.channelDisconnected(SslHandler.java:583)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Config Updated and Logstash  restarted**: stalls here forever, es node is unresponsive
```
[2016-06-17 21:03:43,288][DEBUG][netty.handler.ssl.SslHandler] [id: 0x59b44ca0, /my.ip.add.ress:46102 => /10.0.0.4:9200] HANDSHAKEN: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.http.XFFResolver] xff resolve /my.ip.add.ress:46102
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.http.XFFResolver] no xff done true,false,class org.elasticsearch.http.netty.NettyHttpRequest,{}
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] Try to extract auth creds from http basic 
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'logstash' is in cache? true (cache size: 2)
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.auth.BackendRegistry] User 'User [name=logstash, roles=[]]' is authenticated
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] evaluate permissions for User [name=logstash, roles=[]]
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested indices:admin/template/get from my.ip.add.ress:46102
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] class org.elasticsearch.action.admin.indices.template.get.GetIndexTemplatesRequest is not an IndicesRequest
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved aliases and indices: [_all]
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] requested resolved types: [_all]
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] mapped roles: [sg_logstash, sg_public]
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator] ---------- evaluate sg_role: sg_logstash
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   resolved cluster actions:[indices:admin/template/put, indices:admin/template/get]
[2016-06-17 21:03:43,323][DEBUG][com.floragunn.searchguard.configuration.PrivilegesEvaluator]   found a match for 'sg_logstash' and indices:admin/template/get, skip other roles
```

**Comment by floragunncom** [comment]
thanks, will try to reproduce. Can you also post logs from you very first attempt where the tenantX index was created but no permission was configured?

**Comment by floragunncom** [comment]
Cannot reproduce that. Can you test if you can reproduce it without the ``couchdb_changes``plugin? I tried it with 

```
input {
   heartbeat {
      codec => json
      interval => 1
      add_field => {
        "tenant" => "tenant1738"
      }
   }
}
```

**Comment by iboware** [comment]
Hi, I am adding my cluster log from a fresh start with one newly added logstash configuration entry called tenant1293 (new index). I think you can extract the info you need. 

I will try your suggestion and post the details but I don't think it will show the same symptoms since couchdb_changes uses different APIs like bulk API. It may have have some relation to it. I am not sure.
[Alpha.log.zip](https://github.com/floragunncom/search-guard-ssl/files/322019/Alpha.log.zip)


p.s. I have replaced my domain, host and client ip's since this is a public platform.

**Comment by floragunncom** [comment]
I will go through you logs. Maybe you can try one last thing and disable HTTP SSL completely to make sure the issue is SSL related (or even not). I don't think its related to ``possible truncation attack``, this is normally a harmless DEBUG log message.

**Comment by floragunncom** [comment]
For me logstash stalls also during shutdown (``Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed``), but this is related to the couchdb input plugin (and not the output plugin). I get this message even if i remove the elasticsearch output and running logstash with only the ``stdout``output (BTW: I use logstash 2.3.1, don't know what your version is). All other issues i cannot reproduce.

But maybe you hit a problem which was fixed with https://github.com/floragunncom/search-guard/commit/c7e8fbe6a3ea89755f9b540df6287588de8008f8 so maybe you want try the latest snapshot:
https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-2/2.3.3.2-SNAPSHOT/search-guard-2-2.3.3.2-20160619.100710-20.zip

**Comment by iboware** [comment]
My logstash version is 2.3.2. I have tried the latest snapshot, there are some improvements. I can reach HTTP services now but the index error is still there. When I check my elastic HQ panel it shows that there are 5 unassigned and 5 initializing shards, in 4-5 minutes it becomes 5 unassigned and 3 initializing but its not normal. During this period cluster health shown as red. If I remove the index causing problem, cluster health turns to green. I am going to disable HTTP SSL now to check, if it helps and I will update my answer.

**Comment by iboware** [comment]
Disabling HTTP SSL also did not work. I have noticed that I cannot connect to my non-master node, after restarting Logstash. It brakes something but I have no idea, what it is. I am leaving it as it is since we have no resolution for now. I have to use it carefully. Need for couchdb_changes is actually for migration and for a short-term backup during the migration, so it is temporary.

**Comment by iboware** [comment]
Hi, as I said I was trying other methods instead of trying to fix this but during that approach I found something new.

Since I tought that the logstash plugin has a problem with creating new indexes after restarting logstash I have decided to add that index by curl or by an HTTP client, so logstash won't have to create it.
I created an index called tenant735 , the request took so long. After that I went to my ElasticHQ panel and I saw the same situation. Cluster status was red, initializing and unassigned shards was 5. This is for sure also not an error caused by couchdb_changes plugin even if it triggers it. After stopping logstash, elastic search goes mad. These are the last log entries, just for your information.

```
[2016-06-20 20:51:04,978][WARN ][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Vulcan] Someone speaks plaintext instead of ssl, will close the channel
[2016-06-20 20:51:04,979][ERROR][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Vulcan] SSL Problem engine closed
javax.net.ssl.SSLException: engine closed
[2016-06-20 20:57:16,721][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] Cannot resolve [tenant735] so we use the raw values
[2016-06-20 20:57:16,760][INFO ][cluster.metadata         ] [Vulcan] [tenant735] creating index, cause [api], templates [], shards [5]/[1], mappings []
[2016-06-20 20:57:46,786][WARN ][discovery.zen.publish    ] [Vulcan] timed out waiting for all nodes to process published state [1508] (timeout [30s], pending nodes: [{Andoria}{FxQf2F72TSiZRYJE3jNUzA}{999.99.999.99}{999.99.999.99/999.99.999.99:9300}])
[2016-06-20 20:57:46,869][WARN ][cluster.service          ] [Vulcan] cluster state update task [create-index [tenant735], cause [api]] took 30.1s above the warn threshold of 30s
[2016-06-20 20:58:16,882][WARN ][discovery.zen.publish    ] [Vulcan] timed out waiting for all nodes to process published state [1509] (timeout [30s], pending nodes: [{Andoria}{FxQf2F72TSiZRYJE3jNUzA}{999.99.999.99}{999.99.999.99/999.99.999.99:9300}])
[2016-06-20 20:58:16,903][WARN ][cluster.service          ] [Vulcan] cluster state update task [shard-started ([tenant735][1], node[0VTV8FDiSwidfxx72FOkbQ], [P], v[1], s[INITIALIZING], a[id=JeU4sc4kRbuknnC8SF3vvQ], unassigned_info[[reason=INDEX_CREATED], at[2016-06-20T20:57:16.760Z]]), reason [after recovery from store]] took 30s above the warn threshold of 30s
[2016-06-20 20:58:46,925][WARN ][discovery.zen.publish    ] [Vulcan] timed out waiting for all nodes to process published state [1510] (timeout [30s], pending nodes: [{Andoria}{FxQf2F72TSiZRYJE3jNUzA}{999.99.999.99}{999.99.999.99/999.99.999.99:9300}])
[2016-06-20 20:58:46,947][WARN ][cluster.service          ] [Vulcan] cluster state update task [shard-started ([tenant735][3], node[0VTV8FDiSwidfxx72FOkbQ], [P], v[1], s[INITIALIZING], a[id=O_ORHLvySWKfoDGYP3ku8g], unassigned_info[[reason=INDEX_CREATED], at[2016-06-20T20:57:16.760Z]]), reason [after recovery from store],shard-started ([tenant735][3], node[0VTV8FDiSwidfxx72FOkbQ], [P], v[1], s[INITIALIZING], a[id=O_ORHLvySWKfoDGYP3ku8g], unassigned_info[[reason=INDEX_CREATED], at[2016-06-20T20:57:16.760Z]]), reason [master {Vulcan}{0VTV8FDiSwidfxx72FOkbQ}{888.888.888.88}{elastic1.ofisim.com/888.888.888.88:9300} marked shard as initializing, but shard state is [POST_RECOVERY], mark shard as started]] took 30s above the warn threshold of 30s
[2016-06-20 21:01:04,953][WARN ][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Vulcan] Someone speaks plaintext instead of ssl, will close the channel
[2016-06-20 21:01:04,954][ERROR][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Vulcan] SSL Problem engine closed
javax.net.ssl.SSLException: engine closed

```

**Comment by iboware** [comment]
I have finally found the reason, it is not related to search-guard, but it is related to a configuration setting that I added to make ssl.transport work.
I tried every scenario from start after removing search-guard-2 and search-guard-ssl plugins. It happened again. Index creation problem caused by zen discovery. All I had to do was removing network.publish_host property from my configuration file. After that it started to work correctly, but if I remove this search-guard-ssl won't function. At least I have found the answer to this question. You can close this issue.
```
cluster.name: Alpha
node.name: Vulcan
network.host: 0.0.0.0
network.publish_host: elastic1.mydomain.com
discovery.zen.ping.unicast.hosts: ["elastic1.mydomain.com", "elastic2.mydomain.com"]
discovery.zen.minimum_master_nodes: 2
```

**Comment by floragunncom** [comment]
Thx, but still awkward. Maybe you should open an elasticsearch issue for that.

**Comment by iboware** [comment]
Yeah. I have fixed that one too by regenerating my node SSL certificates with ip addresses. Thanks again for your help.

**Comment by neuronring** [comment]
@iboware 

I am getting a similar issue, any idea what could be the problem. 

Here is my config settings in elasticsearch.yml file

> ################################## Custom #####################################
searchguard.ssl.transport.keystore_filepath: node-1-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false

> searchguard.ssl.http.enabled:` true
searchguard.ssl.http.keystore_filepath: node-1-keystore.jks
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: changeit
searchguard.ssl.transport.enable_openssl_if_available: false
searchguard.ssl.http.clientauth_mode: NONE


`[2016-12-01 21:10:29,234][WARN ][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [Elastic-Temp-98512544-1-177857604.ELK-Temp.apps-ops.boitop.cdcdev1.dev..com] Someone speaks plaintext instead of ssl, will close the channel`
